#!/usr/bin/env python3
"""Plot bar chart and Pareto scatter from aggregate CSVs.

Reads `summary.csv` and `pareto.csv` generated by `public/scripts/aggregate_results.py`.
"""

from __future__ import annotations

import argparse
import csv
import os
import pathlib
from typing import Any, Dict, List

# Configure cache dirs prior to importing Matplotlib.
cache_root = pathlib.Path(".cache")
os.environ.setdefault("XDG_CACHE_HOME", str(cache_root))
os.environ.setdefault("MPLCONFIGDIR", str(cache_root / "matplotlib"))
cache_root.mkdir(parents=True, exist_ok=True)
(cache_root / "matplotlib").mkdir(parents=True, exist_ok=True)
(cache_root / "fontconfig").mkdir(parents=True, exist_ok=True)
os.environ.setdefault("FC_CACHEDIR", str(cache_root / "fontconfig"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42


def _read_csv(path: pathlib.Path) -> List[Dict[str, Any]]:
    with path.open() as f:
        reader = csv.DictReader(f)
        return list(reader)


def _to_float(x: Any) -> float | None:
    if x is None:
        return None
    if isinstance(x, (int, float)):
        return float(x)
    s = str(x).strip()
    if s == "" or s.lower() == "none":
        return None
    try:
        return float(s)
    except Exception:
        return None


def plot_bar(summary_rows: List[Dict[str, Any]], out_path: pathlib.Path) -> None:
    # Plot best variant per model by acc_mean
    best: Dict[str, Dict[str, Any]] = {}
    for r in summary_rows:
        model = r.get("model", "")
        acc = _to_float(r.get("acc_mean"))
        if acc is None:
            continue
        if model not in best or acc > _to_float(best[model].get("acc_mean")):
            best[model] = r
    items = sorted(best.items(), key=lambda kv: _to_float(kv[1].get("acc_mean")) or 0.0, reverse=True)
    labels = [m for m, _ in items]
    accs = [(_to_float(r.get("acc_mean")) or 0.0) * 100.0 for _, r in items]
    stds = [(_to_float(r.get("acc_std")) or 0.0) * 100.0 for _, r in items]

    fig, ax = plt.subplots(figsize=(10, 4.5))
    ax.bar(range(len(labels)), accs, yerr=stds, capsize=3)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.set_ylabel("Accuracy (%)")
    ax.set_title("Validation Accuracy (mean±std over seeds)")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


def plot_pareto(pareto_rows: List[Dict[str, Any]], out_path: pathlib.Path, batch: str) -> None:
    xs = []
    ys = []
    labels = []
    sizes = []
    for r in pareto_rows:
        acc = _to_float(r.get("acc_mean"))
        lat = _to_float(r.get(f"latency_ms_{batch}_mean"))
        params = _to_float(r.get("params_total_mean"))
        if acc is None or lat is None:
            continue
        xs.append(lat)
        ys.append(acc * 100.0)
        labels.append(f"{r.get('model')}")
        sizes.append(max(10.0, (params or 1.0) ** 0.5 / 10.0))
    fig, ax = plt.subplots(figsize=(6.5, 5.0))
    ax.scatter(xs, ys, s=[s for s in sizes], alpha=0.7)
    ax.set_xlabel(f"Latency (ms) batch={batch.replace('batch', '')}")
    ax.set_ylabel("Accuracy (%)")
    ax.set_title("Pareto: Accuracy vs Latency")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--in-dir", type=pathlib.Path, default=pathlib.Path("artifacts/aggregate"))
    p.add_argument("--out-dir", type=pathlib.Path, default=pathlib.Path("artifacts/aggregate/plots"))
    p.add_argument("--dataset", type=str, default=None)
    args = p.parse_args()

    summary = _read_csv(args.in_dir / "summary.csv")
    pareto = _read_csv(args.in_dir / "pareto.csv")
    if args.dataset:
        summary = [r for r in summary if r.get("dataset") == args.dataset]
        pareto = [r for r in pareto if r.get("dataset") == args.dataset]

    plot_bar(summary, args.out_dir / "accuracy_bar.png")
    plot_pareto(pareto, args.out_dir / "pareto_batch1.png", batch="batch1")
    plot_pareto(pareto, args.out_dir / "pareto_batch64.png", batch="batch64")
    print(f"Wrote plots -> {args.out_dir}")


if __name__ == "__main__":
    main()
